apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: react
          image: pavanvere/frontend:0.0.7
          imagePullPolicy: Always
          stdin: true
          tty: true
          ports:
            - containerPort: 3000
      restartPolicy: Always