apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      component: frontend
  template:
    metadata:
      labels:
        component: frontend
    spec:
      containers:
        - name: frontend
          image: pavanvere/frontend:0.0.2  #0.0.10 13or 0.0.1
          imagePullPolicy: Always
          stdin: true
          tty: true
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: http://3.233.109.17:8080/api/v1/employees