apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: react
          image: pavanvere/frontend:0.0.1
          imagePullPolicy: Always
          stdin: true
          tty: true
          ports:
            - containerPort: 80
      restartPolicy: Always