apiVersion: v1
kind: Service
metadata:
  name: react
  labels:
    app: react
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30000-32767
      name: http
  selector:
    app: react