apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: react
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /*
            pathType: Prefix # <-- IMPORTANT
            backend:
              service:
                name: react
                port:
                  number: 3000