apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    appdb: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      appdb: mongo
  template:
    metadata:
      labels:
        appdb: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo