apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - name: mongo
              containerPort: 27017
              hostPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: mongo
  name: mongo
spec:
  type: ClusterIP
  ports:
    - port: 27017
      name: db
      targetPort: 27017
  selector:
    name: mongo
    app: mongo