apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
  labels:
    app: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - name: spring
          image: pavanvere/spring:0.0.1
        - name: mongo
          image: mongo
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring
spec:
  #type: Nodeport
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: spring