apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
spec:
  selector:
    matchLabels:
      app: spring
  replicas: 1
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - name: spring
          image: pavanvere/spring:0.0.1
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: spring
spec:
  #type: Nodeport
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: spring